import random
def Continue():
    Again=str(input("Would you like to use this program again? (Yes/No) "))
    if Again=="No":
        return False
    return True
print("This program will generate a random number in a range given by you and you have to guess the number it generated.")
while True:
    Upper=int(input("Enter the upper limit - "))
    Lower=int(input("Enter the lower limit - "))
    while Lower>Upper:
        print("Lower limit cannot be more than Upper limit.")
        Lower=int(input("Enter the lower limit - "))
    Number=random.randint(Lower,Upper)
    Guess=0
    Max_Guess=4
    Try=int(input("Try guessing the number - "))
    while Max_Guess>Guess:
        if Try==Number:
            print ("You have guessed the number correctly!")
            break
        if Try!=Number:
            Try=int(input("Wrong guess, try again - "))
            Guess+=1
            if Max_Guess==Guess:
                print ("You have run out of tries!")
                print ("The number generated by the computer was - ",Number)
                break
    if not Continue():
        break